# Generated by Django 3.1.2 on 2020-10-07 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_number',
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='phone number')),
                ('identity_number', models.CharField(max_length=11, unique=True, verbose_name='identity')),
                ('first_name', models.CharField(max_length=64, verbose_name='first name')),
                ('last_name', models.CharField(max_length=64, verbose_name='last name')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='amount')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='branches.branch', verbose_name='created branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='associated user')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
            },
        ),
    ]
