# Generated by Django 3.1.2 on 2020-10-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201008_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.FloatField(default=0, verbose_name='amount'),
        ),
    ]
