version: '3.7'

services:
  web:
    build:
      .
    command: gunicorn BankManager.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static/
    expose:
      - 8000
    env_file:
      - env
    depends_on:
      - db
      - redis

  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      - POSTGRES_USER=admin_django
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=bank_manager_db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static/
    ports:
      - 1337:80
    depends_on:
      - web

  redis:
    image: redis:alpine

  celery-worker:
    build: .
    command: celery -A BankManager worker -l INFO
    volumes:
      - .:/home/app/web/
    env_file:
      - env
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    command: celery -A BankManager beat -l INFO
    volumes:
      - .:/home/app/web/
    env_file:
      - env
    depends_on:
      - redis
      - web

volumes:
  postgres_data:
  static_volume:
