LOCAL_CELERY_BROKER_URL = None
LOCAL_REDIS_HOST = None
LOCAL_REDIS_PORT = 6379
LOCAL_CELERY_RESULT_BACKEND = None

LOCAL_ALLOWED_HOSTS = []
LOCAL_SECRET = 'mt)sj$&*mz7l(=jqave%5)x_zyc1y_!t&2(0*_$zrv6be9-f5b'

LOCAL_DB_NAME = None
LOCAL_DB_USER = None
LOCAL_DB_PASS = None
LOCAL_DB_HOST = None
LOCAL_DB_PORT = 5432

LOCAL_HOST = 'http://localhost'
LOCAL_PORT = 8000
