# Generated by Django 3.1.2 on 2020-10-09 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('users', '0002_auto_20201008_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(1, 'withdraw'), (2, 'deposit')], default=1, verbose_name='type')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.account', verbose_name='account')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraws', to='branches.branch', verbose_name='branch')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
    ]
